services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    user: "1000:1000"
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=seu_usuario
      - N8N_BASIC_AUTH_PASSWORD=sua_senha
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/home/ollama/.ollama/models
    command: serve
    restart: unless-stopped

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    depends_on:
      - n8n
    restart: unless-stopped